"""Core package exports."""

from clipping.core.constants import (
    SCHEMA_VERSION,
    TARGET_WIDTH,
    TARGET_HEIGHT,
    TARGET_ASPECT_RATIO,
    TARGET_FPS,
    TARGET_LOUDNORM_I,
    TARGET_LOUDNORM_TP,
    TARGET_LOUDNORM_LRA,
)

__all__ = [
    "SCHEMA_VERSION",
    "TARGET_WIDTH",
    "TARGET_HEIGHT",
    "TARGET_ASPECT_RATIO",
    "TARGET_FPS",
    "TARGET_LOUDNORM_I",
    "TARGET_LOUDNORM_TP",
    "TARGET_LOUDNORM_LRA",
]
