"""Public exports for all Clipping Automation Data Contracts."""

from clipping.contracts.campaign import (
    BoundingBox,
    CampaignRuleCategory,
    CampaignRuleSeverity,
    CampaignRule,
    CampaignSpec,
)
from clipping.contracts.perception import (
    WordTimestamp,
    SpeakerSegment,
    RawTranscript,
    DiarizationResult,
    SpeakerAttributedTranscript,
    PerceptionMetadata,
    SceneCut,
    FaceBoundingBox,
    FaceTrack,
    ActiveSpeakerSegment,
    SourceVideoMetadata,
)
from clipping.contracts.director import (
    SpeakerLayout,
    ReframeCropKeyframe,
    ReframePlan,
)
from clipping.contracts.clip import (
    ClipBoundary,
    ClipCandidate,
    CandidateScoreBreakdown,
    ClipScore,
    RankedCandidate,
    ClipSelectionResult,
    ComplianceResult,
)
from clipping.contracts.rendering import (
    SubtitleEvent,
    RenderJob,
    RenderOutput,
)
from clipping.contracts.qa import (
    QASeverity,
    QACheckStatus,
    QAPassStatus,
    QACheck,
    MediaValidationResult,
    StructuralQAResult,
    VisualQAResult,
    AudioQAResult,
    DuplicateFingerprint,
    QAReport,
    QAResult,
)
from clipping.contracts.publishing import (
    ApprovalStatus,
    ApprovalRequest,
    PublishingStatus,
    PublishingJob,
    PublishingResult,
)

__all__ = [
    "BoundingBox",
    "CampaignRuleCategory",
    "CampaignRuleSeverity",
    "CampaignRule",
    "CampaignSpec",
    "WordTimestamp",
    "SpeakerSegment",
    "RawTranscript",
    "DiarizationResult",
    "SpeakerAttributedTranscript",
    "PerceptionMetadata",
    "SceneCut",
    "FaceBoundingBox",
    "FaceTrack",
    "ActiveSpeakerSegment",
    "SourceVideoMetadata",
    "SpeakerLayout",
    "ReframeCropKeyframe",
    "ReframePlan",
    "ClipBoundary",
    "ClipCandidate",
    "CandidateScoreBreakdown",
    "ClipScore",
    "RankedCandidate",
    "ClipSelectionResult",
    "ComplianceResult",
    "SubtitleEvent",
    "RenderJob",
    "RenderOutput",
    "QASeverity",
    "QACheckStatus",
    "QAPassStatus",
    "QACheck",
    "MediaValidationResult",
    "StructuralQAResult",
    "VisualQAResult",
    "AudioQAResult",
    "DuplicateFingerprint",
    "QAReport",
    "QAResult",
    "ApprovalStatus",
    "ApprovalRequest",
    "PublishingStatus",
    "PublishingJob",
    "PublishingResult",
]
